name: Deploy Deno App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout do código
      - name: Checkout code
        uses: actions/checkout@v2

      # Configura o ambiente Deno
      - name: Set up Deno
        uses: denolib/setup-deno@v1
        with:
          deno-version: v1.40.0

      # Instala dependências
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/import_map.json') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      # Rodar o script para gerar os arquivos
      - name: Run Deno script
        run: |
          deno task start

      # Commit e Push dos arquivos gerados
      - name: Commit and push updated files
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/* index.html
          git commit -m "Atualizar arquivos gerados automaticamente"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}