name: Atualizar feed ANAC

on:
  schedule:
    - cron: '0 * * * *'  # Executa a cada hora
  workflow_dispatch:     # Permite execução manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # Cache Deno (versão corrigida)
      - name: Cache dependências Deno
        uses: actions/cache@v3
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/import_map.json') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Executar script principal
        run: deno run --allow-net --allow-write main.ts

      - name: Commit e Push das atualizações
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/ index.html
          git commit -m "Atualização automática do feed" || echo "Sem alterações"
          git push
